// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAl9X80Pf6YqW7YgnV46HLW0ZPXyi2EkY',
    appId: '1:543216451671:web:0ffb69c9aca2bc5be9e312',
    messagingSenderId: '543216451671',
    projectId: 'tasksapp-c4970',
    authDomain: 'tasksapp-c4970.firebaseapp.com',
    storageBucket: 'tasksapp-c4970.appspot.com',
    measurementId: 'G-MSLH1FNTKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDp5vCWc0szvw4MQe_UgE8uBwdLas9L8k',
    appId: '1:543216451671:android:ff8efcba951d3541e9e312',
    messagingSenderId: '543216451671',
    projectId: 'tasksapp-c4970',
    storageBucket: 'tasksapp-c4970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuanppyoRQYVB2Lej1JoPw9rV5apud54',
    appId: '1:543216451671:ios:ea5474e500e0b390e9e312',
    messagingSenderId: '543216451671',
    projectId: 'tasksapp-c4970',
    storageBucket: 'tasksapp-c4970.appspot.com',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuanppyoRQYVB2Lej1JoPw9rV5apud54',
    appId: '1:543216451671:ios:ea5474e500e0b390e9e312',
    messagingSenderId: '543216451671',
    projectId: 'tasksapp-c4970',
    storageBucket: 'tasksapp-c4970.appspot.com',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAl9X80Pf6YqW7YgnV46HLW0ZPXyi2EkY',
    appId: '1:543216451671:web:c6f970cb6aaccb96e9e312',
    messagingSenderId: '543216451671',
    projectId: 'tasksapp-c4970',
    authDomain: 'tasksapp-c4970.firebaseapp.com',
    storageBucket: 'tasksapp-c4970.appspot.com',
    measurementId: 'G-EZL3Y5DYSE',
  );
}
